import { AuthProvider } from "@/provider/auth/AuthContext";
import AuthRouteGuard from "@/provider/auth/AuthRouteGuard";
import I18nProvider from "@/provider/i18n/I18nProvider";
import { ReactQueryProvider } from "@/provider/query/QueryProvider";
import ThemeRegistry from "@/provider/theme/ThemeRegistry";
import { MainLayout } from "@/template";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/favicon.ico",
    apple: "/logo/apple-touch-icon.png",
    shortcut: "/logo/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <AuthProvider>
            <ThemeRegistry>
              <I18nProvider>
                <AuthRouteGuard>
                  <MainLayout>{children}</MainLayout>
                </AuthRouteGuard>
              </I18nProvider>
            </ThemeRegistry>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
